---
# Common variables for all Proxmox hosts

# SSH key configuration
ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_PRIVATE_KEY_FILE') | default('~/.ssh/id_rsa') }}"
ssh_keys_file: "{{ playbook_dir }}/../../ssh_authorized_keys"

# Network defaults
proxmox_management_vlan: 50

# VM Template IDs
ubuntu_template_id: "{{ lookup('env', 'UBUNTU_TEMPLATE_ID') | default('9001') }}"
opnsense_template_id: "{{ lookup('env', 'OPNSENSE_TEMPLATE_ID') | default('9000') }}"

# Storage configuration
storage_pool: "{{ lookup('env', 'PROXMOX_STORAGE_POOL') | default('local-lvm') }}"

# SSH keys for VMs - will be updated by 01_initial_setup.yml
ssh_public_key: "{{ lookup('env', 'TF_VAR_ssh_public_key') | default(lookup('file', ansible_ssh_private_key_file + '.pub', errors='ignore')) }}"

timezone: "{{ lookup('env', 'TF_VAR_timezone') | default('America/New_York') }}"
