---
# Tennessee-specific variables
network_prefix: "{{ lookup('env', 'TN_NETWORK_PREFIX') }}"
proxmox_mgmt_ip: "{{ lookup('env', 'TN_PROXMOX_HOST') }}"
proxmox_mgmt_gw: "{{ lookup('env', 'TN_PROXMOX_HOST') }}"  # Same as host in this setup

# Interface mappings from environment
lan_interface: "{{ lookup('env', 'TN_LAN_INTERFACE') }}"
wan_interface: "{{ lookup('env', 'TN_WAN_INTERFACE') }}"
camera_interface: "{{ lookup('env', 'TN_CAMERA_INTERFACE') }}"
starlink_interface: "{{ lookup('env', 'TN_STARLINK_INTERFACE') }}"

# Location identifier
location: "tennessee"
location_prefix: "tn"
