---
- name: Check if OPNsense image exists
  stat:
    path: /tmp/OPNsense-25.1-dvd-amd64.iso
  register: opnsense_image

- name: Download OPNsense ISO
  get_url:
    url: https://mirror.wdc1.us.leaseweb.net/opnsense/releases/25.1/OPNsense-25.1-dvd-amd64.iso.bz2
    dest: /tmp/OPNsense-25.1-dvd-amd64.iso.bz2
    mode: '0644'
  when: not opnsense_image.stat.exists

- name: Create OPNsense VM template
  shell: >
    bunzip2 /tmp/OPNsense-25.1-dvd-amd64.iso.bz2 &&
    qm create {{ template_id }} --name "{{ template_name }}" --memory 4096 --cores 2 --net0 virtio,bridge=vmbr0 &&
    qm set {{ template_id }} --scsihw virtio-scsi-pci &&
    qm set {{ template_id }} --virtio0 {{ storage_pool }}:32G &&
    qm set {{ template_id }} --bootdisk virtio0 &&
    qm set {{ template_id }} --serial0 socket &&
    qm set {{ template_id }} --ostype l26 &&
    qm set {{ template_id }} --ide2 {{ storage_pool }}:cdrom,media=cdrom &&
    qm importdisk {{ template_id }} /tmp/OPNsense-23.7-dvd-amd64.iso {{ storage_pool }} &&
    qm set {{ template_id }} --cdrom {{ storage_pool }}:vm-{{ template_id }}-disk-1 &&
    qm set {{ template_id }} --boot c --bootdisk virtio0 &&
    qm template {{ template_id }}
  args:
    executable: /bin/bash
  register: template_result
  changed_when: template_result.rc == 0
  failed_when: template_result.rc != 0 and "already exists" not in template_result.stderr

- name: Create a note about OPNsense template
  debug:
    msg: |
      OPNsense template created. To use this template:
      1. Clone it with "qm clone {{ template_id }} NEW_ID --name opnsense"
      2. Add additional network interfaces as needed
      3. Start the VM and complete the installation process
      4. After installation, convert the VM back to a template if desired
  when: template_result.changed
