---
- name: Check if Ubuntu cloud image exists
  stat:
    path: /tmp/ubuntu-noble-server-cloudimg-amd64.img
  register: cloud_image

- name: Download Ubuntu cloud image
  get_url:
    url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    dest: /tmp/ubuntu-noble-server-cloudimg-amd64.img
    mode: '0644'
  when: not cloud_image.stat.exists

- name: Install required tools
  apt:
    name: 
      - libguestfs-tools
    state: present

- name: Customize cloud image
  shell: >
    virt-customize -a /tmp/ubuntu-noble-server-cloudimg-amd64.img
    --install qemu-guest-agent,openjdk-17-jre,curl
    --update
  args:
    executable: /bin/bash

- name: Create VM template
  shell: >
    qm create {{ template_id }} --name "{{ template_name }}" --memory 1024 --cores 1 --net0 virtio,bridge=vmbr0 &&
    qm importdisk {{ template_id }} /tmp/ubuntu-noble-server-cloudimg-amd64.img {{ storage_pool }} &&
    qm set {{ template_id }} --scsihw virtio-scsi-pci --virtio0 {{ storage_pool }}:vm-{{ template_id }}-disk-0 &&
    qm set {{ template_id }} --agent 1 &&
    qm set {{ template_id }} --ide2 {{ storage_pool }}:cloudinit &&
    qm template {{ template_id }}
  args:
    executable: /bin/bash
  register: template_result
  changed_when: template_result.rc == 0
  failed_when: template_result.rc != 0 and "already exists" not in template_result.stderr
