---
# Production Site Configuration
# This file defines a complete site deployment including hardware specs,
# network topology, security policies, and service configurations

site:
  # Basic site information
  name: "production-site"
  display_name: "Production Site - Main Office"
  network_prefix: "10.100"
  domain: "prod.company.local"
  location:
    address: "123 Business Ave, Tech City, TC 12345"
    timezone: "America/New_York"
    coordinates:
      lat: 40.7128
      lng: -74.0060

  # Contact information
  contacts:
    primary:
      name: "IT Administrator"
      email: "admin@company.local"
      phone: "+1-555-0123"
    secondary:
      name: "Network Engineer"
      email: "network@company.local"
      phone: "+1-555-0124"

  # Hardware specifications
  hardware:
    # CPU configuration
    cpu:
      type: "intel_n100"  # or "amd_ryzen", "intel_core", etc.
      cores: 8
      threads: 8
      base_clock: "1.0GHz"
      boost_clock: "3.4GHz"
      tdp: "6W"

    # Memory configuration
    memory:
      total: "32gb"
      type: "ddr4"
      speed: "3200mhz"
      ecc: false

    # Storage configuration
    storage:
      primary:
        type: "nvme_ssd"
        size: "1tb"
        model: "Samsung 980 PRO"
        interface: "pcie_4.0"
      secondary:
        type: "sata_ssd"
        size: "2tb"
        model: "Samsung 870 EVO"
        interface: "sata3"
        purpose: "backup_storage"

    # Network hardware
    network:
      # Physical network interfaces
      interfaces:
        - name: "eth0"
          type: "2.5gbe"
          role: "wan"
          description: "Primary WAN connection"
          mac_address: "aa:bb:cc:dd:ee:01"

        - name: "eth1"
          type: "2.5gbe"
          role: "wan_backup"
          description: "Backup WAN connection"
          mac_address: "aa:bb:cc:dd:ee:02"

        - name: "eth2"
          type: "10gbe"
          role: "lan"
          description: "Main LAN trunk"
          mac_address: "aa:bb:cc:dd:ee:03"
          vlan: [10, 30, 40, 50, 60, 70]

        - name: "eth3"
          type: "10gbe"
          role: "cameras"
          description: "Camera network"
          mac_address: "aa:bb:cc:dd:ee:04"
          vlan: [20]

        - name: "eth4"
          type: "1gbe"
          role: "management"
          description: "Out-of-band management"
          mac_address: "aa:bb:cc:dd:ee:05"

      # VLAN configuration
      vlans:
        - id: 10
          name: "main"
          description: "Main office network"
          subnet: "10.100.10.0/24"
          gateway: "10.100.10.1"
          dhcp:
            enabled: true
            range_start: "10.100.10.100"
            range_end: "10.100.10.200"
            lease_time: "24h"
            dns_servers: ["10.100.10.1", "1.1.1.1", "8.8.8.8"]
          security_level: "trusted"

        - id: 20
          name: "cameras"
          description: "Security camera network"
          subnet: "10.100.20.0/24"
          gateway: "10.100.20.1"
          dhcp:
            enabled: true
            range_start: "10.100.20.50"
            range_end: "10.100.20.100"
            lease_time: "7d"
            dns_servers: ["10.100.20.1"]
          security_level: "isolated"
          internet_access: false

        - id: 30
          name: "iot"
          description: "IoT and smart devices"
          subnet: "10.100.30.0/24"
          gateway: "10.100.30.1"
          dhcp:
            enabled: true
            range_start: "10.100.30.100"
            range_end: "10.100.30.200"
            lease_time: "7d"
            dns_servers: ["10.100.30.1", "1.1.1.1"]
          security_level: "restricted"
          internet_access: true
          bandwidth_limit: "50mbps"

        - id: 40
          name: "guest"
          description: "Guest network"
          subnet: "10.100.40.0/24"
          gateway: "10.100.40.1"
          dhcp:
            enabled: true
            range_start: "10.100.40.100"
            range_end: "10.100.40.200"
            lease_time: "4h"
            dns_servers: ["1.1.1.1", "8.8.8.8"]
          security_level: "untrusted"
          internet_access: true
          bandwidth_limit: "25mbps"
          isolation: true

        - id: 50
          name: "management"
          description: "Network management"
          subnet: "10.100.50.0/24"
          gateway: "10.100.50.1"
          dhcp:
            enabled: false  # Static IPs only
          security_level: "admin"

        - id: 60
          name: "servers"
          description: "Server network"
          subnet: "10.100.60.0/24"
          gateway: "10.100.60.1"
          dhcp:
            enabled: false  # Static IPs only
          security_level: "trusted"

        - id: 70
          name: "voip"
          description: "VoIP phones"
          subnet: "10.100.70.0/24"
          gateway: "10.100.70.1"
          dhcp:
            enabled: true
            range_start: "10.100.70.100"
            range_end: "10.100.70.150"
            lease_time: "7d"
            dns_servers: ["10.100.70.1"]
          security_level: "trusted"
          qos_priority: "high"

  # WAN configuration
  wan:
    primary:
      type: "fiber"
      provider: "ISP Provider 1"
      speed_down: "1000mbps"
      speed_up: "1000mbps"
      static_ip: true
      ip_address: "203.0.113.100"
      subnet_mask: "255.255.255.248"
      gateway: "203.0.113.97"
      dns_servers: ["203.0.113.98", "203.0.113.99"]

    backup:
      type: "cable"
      provider: "ISP Provider 2"
      speed_down: "500mbps"
      speed_up: "50mbps"
      static_ip: false
      failover_mode: "automatic"
      failover_threshold: "30s"

  # Proxmox configuration
  proxmox:
    host: "10.100.50.10"
    port: 8006
    node_name: "pve-prod"
    api_user: "root@pam"
    api_secret_env: "PROXMOX_API_SECRET"
    ssl_verify: true

    # Storage configuration
    storage:
      local:
        type: "dir"
        path: "/var/lib/vz"
        content: ["images", "iso", "vztmpl"]

      local_ssd:
        type: "dir"
        path: "/mnt/ssd"
        content: ["images", "rootdir"]

      backup:
        type: "dir"
        path: "/mnt/backup"
        content: ["backup"]

    # Network bridges
    bridges:
      vmbr0:
        description: "WAN Bridge"
        ports: ["eth0"]
        vlan_aware: false

      vmbr1:
        description: "WAN Backup Bridge"
        ports: ["eth1"]
        vlan_aware: false

      vmbr2:
        description: "LAN Bridge"
        ports: ["eth2"]
        vlan_aware: true
        vlans: [10, 30, 40, 50, 60, 70]

      vmbr3:
        description: "Camera Bridge"
        ports: ["eth3"]
        vlan_aware: true
        vlans: [20]

  # VM Templates and Services
  vm_templates:
    opnsense:
      enabled: true
      template_id: 9001
      name: "opnsense-prod"
      description: "OPNsense Firewall"
      cores: 4
      memory: 8192
      disk_size: "32G"
      storage: "local_ssd"
      start_on_deploy: true
      start_on_boot: true
      network:
        - bridge: "vmbr0"
          model: "virtio"
          tag: null
        - bridge: "vmbr1"
          model: "virtio"
          tag: null
        - bridge: "vmbr2"
          model: "virtio"
          tag: null
        - bridge: "vmbr3"
          model: "virtio"
          tag: null
      cloud_init:
        enabled: false

    tailscale:
      enabled: true
      template_id: 9002
      name: "tailscale-prod"
      description: "Tailscale VPN Router"
      cores: 1
      memory: 1024
      disk_size: "8G"
      storage: "local_ssd"
      start_on_deploy: true
      start_on_boot: true
      network:
        - bridge: "vmbr2"
          model: "virtio"
          tag: 50
      cloud_init:
        enabled: true
        user: "admin"
        ssh_keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQ..."]

    zeek:
      enabled: true
      template_id: 9003
      name: "zeek-prod"
      description: "Zeek Network Monitor"
      cores: 4
      memory: 8192
      disk_size: "100G"
      storage: "local_ssd"
      start_on_deploy: false
      start_on_boot: false
      network:
        - bridge: "vmbr2"
          model: "virtio"
          tag: 50
        - bridge: "vmbr0"
          model: "virtio"
          tag: null
          promiscuous: true
        - bridge: "vmbr1"
          model: "virtio"
          tag: null
          promiscuous: true
      cloud_init:
        enabled: true
        user: "zeek"
        ssh_keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQ..."]

    homeassistant:
      enabled: true
      template_id: 9004
      name: "homeassistant-prod"
      description: "Home Assistant"
      cores: 2
      memory: 4096
      disk_size: "32G"
      storage: "local_ssd"
      start_on_deploy: true
      start_on_boot: true
      network:
        - bridge: "vmbr2"
          model: "virtio"
          tag: 10
      cloud_init:
        enabled: true
        user: "homeassistant"
        ssh_keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQ..."]

    unifi:
      enabled: true
      template_id: 9005
      name: "unifi-prod"
      description: "UniFi Network Controller"
      cores: 2
      memory: 2048
      disk_size: "16G"
      storage: "local_ssd"
      start_on_deploy: true
      start_on_boot: true
      network:
        - bridge: "vmbr2"
          model: "virtio"
          tag: 50
      cloud_init:
        enabled: true
        user: "unifi"
        ssh_keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQ..."]

  # OPNsense Configuration
  opnsense:
    host: "10.100.50.1"
    api_key_env: "OPNSENSE_API_KEY"
    api_secret_env: "OPNSENSE_API_SECRET"
    web_gui_port: 443
    ssh_port: 22

    # Interface assignments
    interfaces:
      wan:
        device: "vtnet0"
        description: "WAN"
        ipv4_type: "static"
        ipv4_address: "203.0.113.100"
        ipv4_subnet: "29"
        ipv4_gateway: "203.0.113.97"

      wan_backup:
        device: "vtnet1"
        description: "WAN Backup"
        ipv4_type: "dhcp"
        enabled: true

      lan:
        device: "vtnet2"
        description: "LAN"
        ipv4_type: "static"
        ipv4_address: "10.100.10.1"
        ipv4_subnet: "24"

      cameras:
        device: "vtnet3"
        description: "Cameras"
        ipv4_type: "static"
        ipv4_address: "10.100.20.1"
        ipv4_subnet: "24"

    # Firewall rules
    firewall_rules:
      # WAN rules
      - interface: "wan"
        direction: "in"
        action: "block"
        protocol: "any"
        source: "any"
        destination: "any"
        description: "Block all inbound by default"

      - interface: "wan"
        direction: "in"
        action: "pass"
        protocol: "tcp"
        source: "any"
        destination: "wan_address"
        destination_port: "443"
        description: "Allow HTTPS to firewall"

      # LAN rules
      - interface: "lan"
        direction: "in"
        action: "pass"
        protocol: "any"
        source: "lan_subnets"
        destination: "any"
        description: "Allow LAN to any"

      # IoT rules
      - interface: "lan"
        direction: "in"
        action: "block"
        protocol: "any"
        source: "10.100.30.0/24"
        destination: "10.100.10.0/24"
        description: "Block IoT to Main LAN"

      - interface: "lan"
        direction: "in"
        action: "pass"
        protocol: "tcp"
        source: "10.100.30.0/24"
        destination: "any"
        destination_port: "80,443"
        description: "Allow IoT HTTP/HTTPS"

      # Guest rules
      - interface: "lan"
        direction: "in"
        action: "block"
        protocol: "any"
        source: "10.100.40.0/24"
        destination: "10.100.0.0/16"
        description: "Block Guest to internal networks"

      - interface: "lan"
        direction: "in"
        action: "pass"
        protocol: "any"
        source: "10.100.40.0/24"
        destination: "!10.100.0.0/16"
        description: "Allow Guest to Internet"

      # Camera rules
      - interface: "cameras"
        direction: "in"
        action: "block"
        protocol: "any"
        source: "10.100.20.0/24"
        destination: "!10.100.20.0/24"
        description: "Block cameras from other networks"

      - interface: "lan"
        direction: "in"
        action: "pass"
        protocol: "tcp"
        source: "10.100.10.0/24"
        destination: "10.100.20.0/24"
        destination_port: "80,443,554,8000"
        description: "Allow LAN to cameras"

  # Security policies
  security:
    # Password policies
    passwords:
      min_length: 12
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_symbols: true
      expiry_days: 90

    # SSH configuration
    ssh:
      port: 22
      permit_root_login: false
      password_authentication: false
      key_only: true
      max_auth_tries: 3

    # SSL/TLS configuration
    ssl:
      min_version: "1.2"
      ciphers: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256"

    # Intrusion detection
    ids:
      enabled: true
      mode: "inline"
      rulesets: ["emerging-threats", "snort-community"]

    # VPN configuration
    vpn:
      wireguard:
        enabled: true
        port: 51820
        network: "10.100.200.0/24"

      openvpn:
        enabled: false

  # Monitoring and logging
  monitoring:
    # Prometheus metrics
    prometheus:
      enabled: true
      port: 9090
      retention: "30d"

    # Grafana dashboards
    grafana:
      enabled: true
      port: 3000

    # Log management
    logging:
      syslog_server: "10.100.50.20"
      log_level: "info"
      retention_days: 90

    # SNMP monitoring
    snmp:
      enabled: true
      community: "public"
      version: "2c"

  # Backup configuration
  backup:
    # VM backups
    vm_backup:
      enabled: true
      schedule: "daily"
      time: "02:00"
      retention: 7
      compression: "lzo"

    # Configuration backups
    config_backup:
      enabled: true
      schedule: "daily"
      time: "01:00"
      retention: 30
      destination: "/mnt/backup/configs"

  # Maintenance windows
  maintenance:
    # Automatic updates
    auto_updates:
      enabled: true
      schedule: "weekly"
      day: "sunday"
      time: "03:00"
      reboot_if_required: true

    # Maintenance notifications
    notifications:
      email: ["admin@company.local", "network@company.local"]
      slack_webhook: "https://hooks.slack.com/services/..."

# Deployment metadata
deployment:
  version: "1.0.0"
  created_by: "IT Administrator"
  created_date: "2024-01-15"
  last_modified: "2024-06-08"
  environment: "production"

  # Deployment phases
  phases:
    - name: "infrastructure"
      description: "Deploy Proxmox and base infrastructure"
      order: 1

    - name: "networking"
      description: "Configure network bridges and VLANs"
      order: 2

    - name: "firewall"
      description: "Deploy and configure OPNsense"
      order: 3

    - name: "services"
      description: "Deploy additional services"
      order: 4

    - name: "monitoring"
      description: "Setup monitoring and logging"
      order: 5

    - name: "validation"
      description: "Validate deployment and connectivity"
      order: 6

# Compliance and documentation
compliance:
  standards: ["ISO27001", "NIST", "CIS"]
  audit_log: true
  change_management: true

documentation:
  network_diagram: "docs/network-topology.pdf"
  runbook: "docs/operations-runbook.md"
  disaster_recovery: "docs/disaster-recovery-plan.md"
