site:
  name: "test-site"
  network_prefix: "10.99"
  domain: "test.local"
  display_name: "Test Site"
  hardware:
    cpu:
      type: "n100"
      cores: 4
    memory:
      total: "8gb"
    storage:
      type: "ssd"
      size: "128gb"
    network:
      interfaces:
        - name: "eth0"
          type: "2.5gbe"
          role: "wan"
        - name: "eth1"
          type: "2.5gbe"
          role: "wan_backup"
        - name: "eth2"
          type: "10gbe"
          role: "lan"
          vlan: [10, 30, 40, 50]
        - name: "eth3"
          type: "10gbe"
          role: "cameras"
          vlan: [20]
      vlans:
        - id: 10
          name: "main"
          subnet: "10.99.10.0/24"
        - id: 20
          name: "cameras"
          subnet: "10.99.20.0/24"
        - id: 30
          name: "iot"
          subnet: "10.99.30.0/24"
        - id: 40
          name: "guest"
          subnet: "10.99.40.0/24"
        - id: 50
          name: "management"
          subnet: "10.99.50.0/24"
  proxmox:
    host: "proxmox-mock"
    node_name: "pve"
    api_secret_env: "PROXMOX_API_SECRET"
