name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels:
  - "enhancement"
  - "needs-triage"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the documentation to confirm this feature doesn't already exist
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Network Configuration
        - Security Enhancement
        - Monitoring/Logging
        - VM Management
        - Device Support
        - Automation/Scripts
        - User Interface
        - Documentation
        - Performance
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or limitation you're experiencing.
        Example: "Currently, there's no way to automatically backup device configurations..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: |
        Describe how you'd like this feature to work.
        Be as specific as possible about the desired behavior.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        Describe any alternative solutions or workarounds you've considered.
        Why wouldn't these alternatives work?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current use case
        - Critical - Required for production use
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: |
        Provide context about how you would use this feature:
        - What is your setup/environment?
        - How often would you use this feature?
        - What would be the impact of having this feature?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        If you have technical knowledge, share your thoughts on:
        - Which components would need changes
        - Configuration options needed
        - Integration points
        - Potential challenges

  - type: textarea
    id: examples
    attributes:
      label: Examples/References
      description: Are there examples of this feature in other projects?
      placeholder: |
        Provide links or references to:
        - Similar features in other projects
        - Documentation or specifications
        - Screenshots or mockups
        - Code examples

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request to implement this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false
