# Site Configuration Template
# Copy this file to sites/your-site-name.yml and customize for your site
# This is the single source of truth for your site - no other config files needed!
#
# IMPORTANT: Replace "10.x" throughout this file with your actual network prefix
# Examples:
#   - For 192.168.x.x networks: change "10.x" to "192.168"
#   - For 10.1.x.x networks: change "10.x" to "10.1"
#   - For 172.16.x.x networks: change "10.x" to "172.16"

site:
  name: "your-site-name"           # Short name (lowercase, no spaces)
  display_name: "Your Site Name"   # Human-readable name
  network_prefix: "10.x"           # First two octets of your network - use "10.x" as placeholder, replace with actual like "10.1", "192.168", etc.
  domain: "yoursite.local"         # Local domain name

  # Hardware Configuration
  hardware:
    cpu:
      type: "n100"                 # CPU type identifier
      cores: 4                     # Number of CPU cores
      threads: 4                   # Number of CPU threads

    memory:
      total: "8gb"                 # Total system memory
      vm_allocation:               # Memory allocation per VM
        opnsense: "4gb"
        tailscale: "1gb"
        zeek: "2gb"
        homeassistant: "1gb"

    storage:
      type: "ssd"                  # Storage type (ssd, nvme, hdd)
      size: "128gb"                # Total storage size
      allocation:                  # Storage allocation
        system: "20gb"
        vms: "80gb"
        backups: "28gb"

    network:
      interfaces:                  # Physical network interfaces
        - name: "eth0"
          type: "2.5gbe"
          role: "wan"
          vlan: null
        - name: "eth1"
          type: "2.5gbe"
          role: "wan_backup"
          vlan: null
        - name: "eth2"
          type: "10gbe"
          role: "lan"
          vlan: [10, 30, 40, 50]
        - name: "eth3"
          type: "10gbe"
          role: "cameras"
          vlan: [20]

      vlans:                       # VLAN definitions
        - id: 10
          name: "main"
          subnet: "10.x.10.0/24"     # Replace 10.x with your network_prefix
          dhcp: true
          gateway: "10.x.10.1"       # Replace 10.x with your network_prefix
        - id: 20
          name: "cameras"
          subnet: "10.x.20.0/24"     # Replace 10.x with your network_prefix
          dhcp: true
          gateway: "10.x.20.1"       # Replace 10.x with your network_prefix
        - id: 30
          name: "iot"
          subnet: "10.x.30.0/24"     # Replace 10.x with your network_prefix
          dhcp: true
          gateway: "10.x.30.1"       # Replace 10.x with your network_prefix
        - id: 40
          name: "guest"
          subnet: "10.x.40.0/24"     # Replace 10.x with your network_prefix
          dhcp: true
          gateway: "10.x.40.1"       # Replace 10.x with your network_prefix
        - id: 50
          name: "management"
          subnet: "10.x.50.0/24"     # Replace 10.x with your network_prefix
          dhcp: true
          gateway: "10.x.50.1"       # Replace 10.x with your network_prefix

      bridges:                     # Proxmox bridge definitions
        - name: "vmbr0"
          interface: "eth0"
          description: "WAN Bridge"
        - name: "vmbr1"
          interface: "eth2"
          description: "LAN Bridge"
          vlans: [10, 30, 40, 50]
        - name: "vmbr2"
          interface: "eth3"
          description: "Camera Bridge"
          vlans: [20]
        - name: "vmbr3"
          interface: "eth1"
          description: "WAN Backup Bridge"

  # Proxmox Configuration
  proxmox:
    host: "10.x.1.100"             # IP address or hostname of your Proxmox server (replace 10.x with your network_prefix)
    node_name: "pve"               # Proxmox node name
    storage_pool: "local-lvm"      # Storage pool for VMs
    template_storage: "local"      # Storage for VM templates

  # VM Templates
  vm_templates:
    opnsense:                      # OPNsense firewall VM
      enabled: true
      template_id: 9000
      cores: 4
      memory: 4096
      disk_size: "32G"
      start_on_deploy: true
      network:
        - bridge: "vmbr0"
          model: "virtio"
        - bridge: "vmbr1"
          model: "virtio"
        - bridge: "vmbr2"
          model: "virtio"
        - bridge: "vmbr3"
          model: "virtio"

    tailscale:                     # Tailscale VPN VM
      enabled: true
      template_id: 9001
      cores: 1
      memory: 1024
      disk_size: "8G"
      start_on_deploy: true
      network:
        - bridge: "vmbr1"
          model: "virtio"
          vlan: 50

    zeek:                          # Zeek network monitoring VM
      enabled: true
      template_id: 9001
      cores: 2
      memory: 2048
      disk_size: "50G"
      start_on_deploy: false       # Don't auto-start (resource intensive)
      network:
        - bridge: "vmbr1"
          model: "virtio"
          vlan: 50
        - bridge: "vmbr0"
          model: "virtio"
          promiscuous: true        # For network monitoring

    homeassistant:                 # Home Assistant VM (optional)
      enabled: false               # Disabled by default
      template_id: 9001
      cores: 2
      memory: 1024
      disk_size: "16G"
      start_on_deploy: false
      network:
        - bridge: "vmbr1"
          model: "virtio"
          vlan: 10

  # Security Configuration
  security:
    firewall:
      default_policy: "deny"       # Default deny all traffic
      rules:                       # Custom firewall rules
        - name: "Allow LAN to WAN"
          source: "10.x.10.0/24"     # Replace 10.x with your network_prefix
          destination: "any"
          action: "allow"
        - name: "Block IoT to LAN"
          source: "10.x.30.0/24"     # Replace 10.x with your network_prefix
          destination: "10.x.10.0/24"  # Replace 10.x with your network_prefix
          action: "deny"
        - name: "Allow Guest Internet Only"
          source: "10.x.40.0/24"     # Replace 10.x with your network_prefix
          destination: "!10.x.0.0/16"  # Replace 10.x with your network_prefix (block access to local network)
          action: "allow"

    suricata:                      # Intrusion detection system
      enabled: true
      interfaces: ["WAN", "WAN_BACKUP"]
      ruleset: "emerging-threats"

  # Monitoring Configuration
  monitoring:
    enabled: true
    retention_days: 30             # How long to keep monitoring data
    alerts:
      email: "admin@yoursite.local"  # Update with your email
      webhook: null                # Optional webhook URL

  # Backup Configuration
  backup:
    enabled: true
    schedule: "0 2 * * *"          # Daily at 2 AM (cron format)
    retention: 7                   # Keep 7 days of backups
    destination: "local"           # Backup destination

  # Credentials (environment variable names - actual values go in .env file)
  credentials:
    proxmox_api_secret: "YOUR_SITE_NAME_PROXMOX_API_SECRET"  # Update YOUR_SITE_NAME
    tailscale_auth_key: "TAILSCALE_AUTH_KEY"
    ssh_public_key_file: "credentials/your-site-name_root.pub"   # Update your-site-name
    ssh_private_key_file: "credentials/your-site-name_root"      # Update your-site-name
