---
- name: Create VM Templates
  hosts: proxmox
  become: true
  tasks:
    - name: Create Ubuntu template for Omada/Tailscale
      ansible.builtin.include_role:
        name: vm_templates
        tasks_from: ubuntu_cloud
      vars:
        vm_templates_template_id: "{{ ubuntu_template_id }}"
        vm_templates_template_name: "ubuntu-cloud-template"

    - name: Create OPNsense template
      ansible.builtin.include_role:
        name: vm_templates
        tasks_from: opnsense
      vars:
        vm_templates_template_id: "{{ opnsense_template_id }}"
        vm_templates_template_name: "opnsense-template"
