---
- name: Deploy VMs using Terraform
  hosts: localhost
  tasks:
    - name: Ensure Terraform directory exists
      file:
        path: "{{ playbook_dir }}/../terraform"
        state: directory
        
    - name: Create terraform.tfvars for each environment
      template:
        src: templates/terraform.tfvars.j2
        dest: "{{ playbook_dir }}/../terraform/{{ item }}.tfvars"
      loop:
        - tennessee
        - primary_home
      
    - name: Initialize Terraform
      shell: terraform init
      args:
        chdir: "{{ playbook_dir }}/../terraform"
        
    - name: Deploy Tennessee environment
      shell: terraform apply -var-file=tennessee.tfvars -auto-approve
      args:
        chdir: "{{ playbook_dir }}/../terraform"
      
    - name: Deploy Primary Home environment
      shell: terraform apply -var-file=primary_home.tfvars -auto-approve
      args:
        chdir: "{{ playbook_dir }}/../terraform"
