global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'proxmox-mock'
    static_configs:
      - targets: ['proxmox-mock:8006']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'opnsense-mock'
    static_configs:
      - targets: ['opnsense-mock:443']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'network-sim'
    static_configs:
      - targets: ['network-sim:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'test-runner'
    static_configs:
      - targets: ['test-runner:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
