#!/bin/bash
# prerequisites.sh - Install required packages and Python dependencies
#
# This script installs all necessary packages and Python modules
# required for the Proxmox Firewall deployment system.

set -e

# Ensure we're running from the project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"

# Change to project root if not already there
if [ "$(pwd)" != "$PROJECT_ROOT" ]; then
    echo "Changing to project root: $PROJECT_ROOT"
    cd "$PROJECT_ROOT"
fi

# Color configuration
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Banner
echo -e "${BLUE}============================================================${NC}"
echo -e "${BLUE}       Proxmox Firewall - Prerequisites Installation        ${NC}"
echo -e "${BLUE}============================================================${NC}"

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to install Python package
install_python_package() {
    echo -e "${YELLOW}Installing Python package: $1${NC}"
    pip3 install "$1"
}

# Update package lists (requires sudo)
echo -e "\n${GREEN}Updating package lists...${NC}"
# Install required tools (if not already present)
# Add the Proxmox VE repository as root:
echo "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription" | sudo tee /etc/apt/sources.list.d/pve-install-repo.list

# Import the Proxmox VE signing key:
sudo wget http://download.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg

sudo apt-get update

# Install required system packages (requires sudo)
echo -e "\n${GREEN}Installing required system packages...${NC}"
sudo apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    pipx \
    curl \
    wget \
    jq \
    yq \
    xorriso \
    whois \
    proxmox-auto-install-assistant


# Install Python packages
echo -e "\n${GREEN}Installing required Python packages...${NC}"
##NONE

# Create necessary directories (as user)
echo -e "\n${GREEN}Creating necessary directories...${NC}"
mkdir -p config/sites
mkdir -p config/devices
mkdir -p credentials
mkdir -p deployment/ansible/group_vars
mkdir -p terraform/states

# Set up Python virtual environment (as user)
echo -e "\n${GREEN}Setting up Python virtual environment...${NC}"
python3 -m venv venv
source venv/bin/activate

# Install additional Python packages in virtual environment (as user)
pipx ensurepath
pipx install --force --include-deps ansible
pipx install --force ansible-dev-tools ansible-lint
pip install --force httpx proxmoxer requests paramiko python-dotenv

ansible-galaxy collection install -r deployment/ansible/collections/requirements.yml

# Create .env file if it doesn't exist (as user)
if [ ! -f .env ]; then
    echo -e "\n${GREEN}Creating .env file template...${NC}"
    cat > .env <<EOL
# Proxmox Firewall - Site Configuration Environment Variables
# This file contains site-specific environment variables used by Ansible and Terraform

# Global Configuration
ANSIBLE_SSH_PRIVATE_KEY_FILE=~/.ssh/id_rsa
TAILSCALE_AUTH_KEY=""  # Get from Tailscale admin console

# Site-specific Proxmox API Secrets (generated by Ansible during setup)
# Format: {SITE_NAME}_PROXMOX_API_SECRET
# These will be populated automatically when you run the Terraform API setup

# Example for sites (uncomment and update as needed):
# SH_PROXMOX_API_SECRET=""     # Secondary site
# PH_PROXMOX_API_SECRET=""     # Primary Home site

# SSH Key Configuration
TF_VAR_ssh_private_key_file="\${ANSIBLE_SSH_PRIVATE_KEY_FILE}"

# Add your site-specific variables here after running create_site_config.sh
EOL
    echo -e "${YELLOW}Note:${NC} Proxmox API secrets will be automatically added when you run the Terraform API setup playbooks"
fi

# Check if SSH key exists (as user)
if [ ! -f ~/.ssh/id_rsa ]; then
    echo -e "\n${YELLOW}No SSH key found. Generating new SSH key...${NC}"
    ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
    echo -e "${GREEN}SSH key generated. Public key:${NC}"
    cat ~/.ssh/id_rsa.pub
fi

echo -e "\n${GREEN}Prerequisites installation completed successfully!${NC}"
echo -e "${YELLOW}Next steps:${NC}"
echo -e "1. Run ./vendor/proxmox-firewall/deployment/scripts/download_latest_images.sh to download latest images"
echo -e "2. Run ./vendor/proxmox-firewall/deployment/scripts/create_site_config.sh to configure your sites"
